name: Update GitHub Activity

on:
  schedule:
    - cron: "0 */1 * * *" # Runs every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update this repo's README with recent activity

    steps:
      - uses: actions/checkout@v6
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          MIN_LINES: 5
          MAX_LINES: 10
